# charts/stock-app/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    # EKS에서 Service Type: LoadBalancer 사용 시 ALB(Application Load Balancer)를 프로비저닝하도록 명시
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-llm-service
  labels:
    app: llm-chatbot
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: {{ .Values.llm.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: llm-chatbot