# charts/stock-app/templates/service.yaml

# 1. 백엔드 API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: backend
spec:
  type: ClusterIP # ⬅️ [수정]: Ingress 사용을 위해 ClusterIP로 변경
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: backend

---

# 2. 프론트엔드 Web Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    app: frontend
spec:
  type: ClusterIP # ⬅️ [수정]: ClusterIP로 변경
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: frontend

---

# 3. LLM 챗봇 API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-llm-service
  labels:
    app: llm-chatbot
spec:
  type: ClusterIP # ⬅️ [수정]: ClusterIP로 변경
  ports:
    - port: 80
      targetPort: {{ .Values.llm.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: llm-chatbot